blank_issues_enabled: false
contact_links:
  - name: Release Team Awesome
    url: https://broken.url
    about: Cat Specialists
  - name: Engineering Services
    url: https://broken.url
    about: Awesome People making amazing things
