name: I Need a Taco
description: Love Tacos? We do too!
title: "[TACO]: "
labels: ["taco"]
body:
  - type: markdown
    attributes: 
      value: |
        Tacos!
  - type: dropdown
    id: tacos
    attributes:
      label: Tacos?
      options:
        - "Yes"
        - "Please"
    validations:
      required: true

