name: Enable CRT on New Repository
description: Enable CRT on New Repository
title: "[CRT]: "
labels: 
  - "crt"
body:
  - type: markdown
    attributes: 
      value: |
        Thank you for using CRT
  - type: input 
    id: repository
    attributes:
      label: Repository
      description: The repository in the hashicorp org to enable CRT on
      placeholder: crt-core-helloworld
    validations: 
      required: true
  - type: input
    id: team-name
    attributes:
      label: Team Name
      description: The team repsonsible for shipping this software
    validations:
      required: true

