name: Random Request
description: Have need of something that doesn't fit another category?
title: "[RANDOM]: "
labels: ["random" ]
body:
  - type: markdown
    attributes: 
      value: |
        Thank you for using this thing
  - type: textarea
    id: request
    attributes:
      label: Team Name
      placeholder: Enter your request here

