name: Release Support
description: Request support with an ongoing release
title: "[REL]: "
labels: ["release", "urgent" ]
body:
  - type: markdown
    attributes: 
      value: |
        Thank you for using this thing
  - type: input
    id: slack-channel
    attributes:
      label: slack-channel
      description: Where can we reach you in slack?
    validations:
      required: true
  - type: input 
    id: workflow
    attributes:
      label: workflow
      description: URL of the workflow that is failing
  - type: textarea
    id: additional-info
    attributes:
      label: additional-info
      description: Any additional information that will help us unblock you
