name: Work Order Type 1
description: Work Orders for type one work
title: "[ONE]: "
labels: ["one", "work_order" ]
body:
  - type: markdown
    attributes: 
      value: |
        Thank you for using this thing
  - type: input 
    id: repository
    attributes:
      label: Repository
      description: The repository that needs type one work
      placeholder: issues-playground
    validations: 
      required: true
  - type: input
    id: team-name
    attributes:
      label: Team Name
      description: The team repsonsible for this repository
    validations:
      required: true

