---
on: 
  issues:
    types: [opened, edited]


jobs: 
  taco:
    if: ${{ contains(github.event.issue.labels.*.name, 'taco') }}
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{github.token}}
    steps:
      - name: Serve Taco
        run: | 
          .github/scripts/post_a_taco.sh "${{ github.event.issue.comments_url }}"
      - name: Close Issue
        run: |
          .github/scripts/close_issue.sh "${{ github.event.issue.url }}"
